package com.nxtbattle.rebuild;

import android.content.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends android.app.Activity {
    LinearLayout root, content, nav; TextView title, balance; double wallet=0; final int PURPLE=Color.rgb(108,53,255), TEXT=Color.rgb(23,23,37), MUTED=Color.rgb(115,115,131); android.content.SharedPreferences prefs;
    int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,float z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(TEXT);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
    GradientDrawable gd(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(r));return g;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setAllCaps(false);b.setBackground(gd(PURPLE,14));b.setPadding(dp(14),0,dp(14),0);return b;}
    TextView pill(String s){TextView t=tv(s,13);t.setTextColor(Color.WHITE);t.setGravity(Gravity.CENTER);t.setPadding(dp(12),0,dp(12),0);t.setBackground(gd(PURPLE,30));return t;}
    @Override public void onCreate(Bundle b){super.onCreate(b); prefs=getSharedPreferences("nxt",0);wallet=Double.longBitsToDouble(prefs.getLong("wallet",Double.doubleToLongBits(0))); build(); home();}
    void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(246,247,251));setContentView(root);
      LinearLayout top=new LinearLayout(this);top.setPadding(dp(16),dp(10),dp(16),dp(10));top.setGravity(Gravity.CENTER_VERTICAL);top.setBackgroundColor(PURPLE);
      title=tv("NXT BATTLE",20);title.setTextColor(Color.WHITE);title.setTypeface(null,1);top.addView(title,new LinearLayout.LayoutParams(0,dp(52),1));
      balance=tv("₹ 0.00",16);balance.setTextColor(Color.WHITE);balance.setGravity(Gravity.CENTER);top.addView(balance,new LinearLayout.LayoutParams(dp(110),dp(42)));root.addView(top);
      content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(14),dp(16),dp(8));ScrollView sc=new ScrollView(this);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
      nav=new LinearLayout(this);nav.setPadding(dp(6),dp(4),dp(6),dp(6));nav.setBackgroundColor(Color.WHITE);String[] n={"Home","Games","Wallet","Profile"};for(String x:n){Button q=new Button(this);q.setText(x);q.setTextSize(12);q.setAllCaps(false);q.setTextColor(MUTED);q.setBackgroundColor(Color.TRANSPARENT);q.setOnClickListener(v->{if(x.equals("Home"))home();else if(x.equals("Games"))games();else if(x.equals("Wallet"))wallet();else profile();});nav.addView(q,new LinearLayout.LayoutParams(0,dp(58),1));}root.addView(nav);refreshBalance();}
    void clear(String h){content.removeAllViews();title.setText(h);}
    void refreshBalance(){balance.setText(String.format(Locale.US,"₹ %.2f",wallet));}
    TextView heading(String s){TextView t=tv(s,22);t.setTypeface(null,1);t.setPadding(0,dp(8),0,dp(12));return t;}
    TextView small(String s){TextView t=tv(s,13);t.setTextColor(MUTED);t.setPadding(0,dp(3),0,dp(8));return t;}
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackground(gd(Color.WHITE,18));c.setElevation(dp(2));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));c.setLayoutParams(p);return c;}
    void home(){clear("NXT BATTLE");LinearLayout hero=card();TextView h=tv("Welcome to NXT Battle",24);h.setTypeface(null,1);hero.addView(h);hero.addView(small("Play matches, manage your wallet and track rewards."));Button play=btn("Play Now");play.setOnClickListener(v->games());hero.addView(play,new LinearLayout.LayoutParams(-1,dp(48)));content.addView(hero);
      LinearLayout row=new LinearLayout(this);row.setWeightSum(2);for(String[] a:new String[][]{{"🎮","Games","Join matches"},{"🎁","Rewards","Refer & earn"}}){LinearLayout c=card();TextView i=tv(a[0],28);c.addView(i,new LinearLayout.LayoutParams(-1,dp(42)));c.addView(tv(a[1],17));c.addView(small(a[2]));row.addView(c,new LinearLayout.LayoutParams(0,-2,1));}content.addView(row);
      TextView info=tv("Quick actions",18);info.setTypeface(null,1);content.addView(info);String[] actions={"Add Money","Transactions","Leaderboard","Customer Support"};for(String s:actions){Button x=btn(s);x.setOnClickListener(v->{if(s.equals("Add Money"))payment();else if(s.equals("Transactions"))transactions();else Toast.makeText(this,s+" screen",Toast.LENGTH_SHORT).show();});content.addView(x,new LinearLayout.LayoutParams(-1,dp(48)));}
    }
    void games(){clear("Games");content.addView(heading("Choose a game"));String[][] gs={{"Ludo Battle","Fast multiplayer ludo matches","Play"},{"Quick Battle","Join an available battle","Play"},{"Practice","Practice without wallet entry","Practice"}};for(String[] g:gs){LinearLayout c=card();c.addView(tv(g[0],19));c.addView(small(g[1]));Button b=btn(g[2]);b.setOnClickListener(v->Toast.makeText(this,"Game module ready for backend integration",Toast.LENGTH_SHORT).show());c.addView(b,new LinearLayout.LayoutParams(-1,dp(46)));content.addView(c);}}
    void wallet(){clear("Wallet");content.addView(heading("Wallet"));LinearLayout c=card();TextView a=tv(String.format(Locale.US,"₹ %.2f",wallet),32);a.setTypeface(null,1);c.addView(a);c.addView(small("Available balance"));Button add=btn("+ Add Money");add.setOnClickListener(v->payment());c.addView(add,new LinearLayout.LayoutParams(-1,dp(50)));content.addView(c);Button tr=btn("Transaction History");tr.setOnClickListener(v->transactions());content.addView(tr,new LinearLayout.LayoutParams(-1,dp(48)));}
    void payment(){clear("Add Money");content.addView(heading("Add Coins"));content.addView(small("Enter the amount you want to add to your wallet."));EditText amount=new EditText(this);amount.setHint("Amount (₹)");amount.setInputType(2|8192);amount.setPadding(dp(16),0,dp(16),0);amount.setBackground(gd(Color.WHITE,14));content.addView(amount,new LinearLayout.LayoutParams(-1,dp(54)));content.addView(small("Payment methods"));
      String[] methods={"PhonePe","Google Pay / UPI","UPI QR + Verification"};for(String m:methods){Button b=btn(m);b.setOnClickListener(v->{double a;try{a=Double.parseDouble(amount.getText().toString());}catch(Exception e){a=0;}if(a<=0){Toast.makeText(this,"Enter a valid amount",Toast.LENGTH_SHORT).show();return;}if(m.startsWith("UPI QR"))qr(a);else upi(a,m);});content.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));}
      content.addView(small("Security: wallet credit should occur only after backend/gateway verification."));}
    void upi(double amount,String method){String upi="upi://pay?pa=manojkumarp@fam&pn=manoj%20kumar&am="+String.format(Locale.US,"%.2f",amount)+"&cu=INR";try{startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(upi)));}catch(Exception e){Toast.makeText(this,"No UPI app available",Toast.LENGTH_LONG).show();}Toast.makeText(this,method+" selected. Verify payment on server before crediting wallet.",Toast.LENGTH_LONG).show();}
    void qr(double amount){clear("UPI QR Payment");content.addView(heading("Scan & Pay"));content.addView(small(String.format(Locale.US,"Pay ₹ %.2f using any UPI app, then return here.",amount)));ImageView im=new ImageView(this);im.setImageResource(com.nxtbattle.rebuild.R.drawable.merchant_upi_qr);im.setScaleType(ImageView.ScaleType.CENTER_INSIDE);im.setBackground(gd(Color.WHITE,16));content.addView(im,new LinearLayout.LayoutParams(-1,dp(260)));content.addView(small("Scan this merchant QR with any supported UPI app. Payment is credited only after verification."));Button verify=btn("I Have Paid — Verify");verify.setOnClickListener(v->paymentStatus(amount));content.addView(verify,new LinearLayout.LayoutParams(-1,dp(52)));}
    void paymentStatus(double amount){clear("Payment Verification");content.addView(heading("Payment Submitted"));content.addView(small("Your payment is pending verification. In production, the backend will verify the UTR/transaction with the payment provider before crediting the wallet."));TextView s=tv("STATUS: PENDING",17);s.setTextColor(PURPLE);s.setPadding(0,dp(20),0,dp(20));content.addView(s);Button b=btn("Back to Wallet");b.setOnClickListener(v->wallet());content.addView(b,new LinearLayout.LayoutParams(-1,dp(50)));}
    void transactions(){clear("Transactions");content.addView(heading("Transaction History"));content.addView(small("Verified wallet transactions will appear here."));LinearLayout c=card();c.addView(tv("No verified transactions yet",17));c.addView(small("Payment records will be populated after backend integration."));content.addView(c);}
    void profile(){clear("Profile");content.addView(heading("Profile"));LinearLayout c=card();c.addView(tv("NXT Battle User",20));c.addView(small("Account and wallet settings"));content.addView(c);String[] x={"My Matches","Rewards & Referrals","Leaderboard","Customer Support","Terms & Conditions","Logout"};for(String s:x){Button b=btn(s);b.setOnClickListener(v->Toast.makeText(this,s,Toast.LENGTH_SHORT).show());content.addView(b,new LinearLayout.LayoutParams(-1,dp(48)));}}
}
